### ISSUE TITLE
IPrincipal.Identity.IsAuthenticated always false after OWIN integration

### ISSUE THREAD

**Issue by joelmdev** [autofac/Autofac.WebApi.Owin#3]
I have an app that I have been successfully using Autofac with for MVC and WebAPI controllers. At this point, I need the Autofac to control the service instances that MVC, WebAPI, and OWIN context use. I seem to have gotten most of the way with the OWIN integration, but any controllers or actions decorated with an AuthorizeAttribute now fail. Digging deeper, the check for IPrincipal.Identity.IsAuthenticated is always returning false. This is more or less the Startup.cs, although there's been some flailing as I've tried to get this to work. I can post the Startup.Auth.cs as well if nothing here is telling.

here's my Startup.cs

```
[assembly: OwinStartup(typeof(Startup))]
namespace Project.Web
{
    public partial class Startup
    {
        public void Configuration(IAppBuilder app)
        {
            var builder = new ContainerBuilder();
            builder.RegisterControllers(Assembly.GetExecutingAssembly());
            var config = new HttpConfiguration();
            builder.RegisterHttpRequestMessage(config);
            builder.RegisterApiControllers(Assembly.GetExecutingAssembly());
            RegisterGeneralTypes(builder);
            var container = builder.Build();
            WebApiConfig.Register(config);
            config.DependencyResolver = new AutofacWebApiDependencyResolver(container);
            DependencyResolver.SetResolver(new AutofacDependencyResolver(container));
            WebApiFilterConfig.RegisterGlobalFilters(config.Filters);

            app.UseAutofacMiddleware(container);
            app.UseAutofacWebApi(config);
            app.UseAutofacMvc();
            app.UseWebApi(config);

            ConfigureAuth(app);
        }

        private static void RegisterGeneralTypes(ContainerBuilder builder)
        {
            builder.Register(c => new DomainModelContext())
                .AsSelf()
                .InstancePerRequest();

            builder.Register(c => HttpContext.Current.User.Identity)
                .As(typeof(IIdentity));

            builder.RegisterType<EmailService>()
                .AsImplementedInterfaces()
                .InstancePerRequest();

            builder.Register(c => new IdentityFactoryOptions<DomainUserManager>
            {
                DataProtectionProvider = DataProtectionProvider
            }).InstancePerRequest();

            builder.RegisterType<DomainUserManager>()
                .AsSelf()
                .UsingConstructor(typeof(IIdentityMessageService),
                    typeof(IdentityFactoryOptions<DomainUserManager>),
                    typeof(CustomUserStore))
                .InstancePerRequest();

            builder.RegisterType<CustomUserStore>()
                .AsImplementedInterfaces()
                .AsSelf()
                .InstancePerRequest();

            builder.Register(c => HttpContext.Current.GetOwinContext().Authentication)
                .As<IAuthenticationManager>();
        }
    }
}
```

and my Startup.Auth.cs:

```
public partial class Startup
{
    internal static IDataProtectionProvider DataProtectionProvider;
    public static OAuthAuthorizationServerOptions OAuthOptions { get; private set; }
    public static string PublicClientId { get; private set; }

    public void ConfigureAuth(IAppBuilder app)
    {
        var onValidateIdentity = SecurityStampValidator
            .OnValidateIdentity<DomainUserManager, DomainUser, int>(
                validateInterval: TimeSpan.FromMinutes(30),
                regenerateIdentityCallback: (manager, user) =>
                    user.GenerateUserIdentityAsync(manager, CookieAuthenticationDefaults.AuthenticationType),
                getUserIdCallback: id => id.GetUserId<int>());

        app.UseCookieAuthentication(new CookieAuthenticationOptions
        {
            LoginPath = new PathString("/account/login"),

            Provider = new CookieAuthenticationProvider
            {
                OnValidateIdentity = onValidateIdentity
            }
        });
        app.UseExternalSignInCookie(DefaultAuthenticationTypes.ExternalCookie);

        // Configure the application for OAuth based flow
        PublicClientId = "self";
        OAuthOptions = new OAuthAuthorizationServerOptions
        {
            TokenEndpointPath = new PathString("/token"),
            Provider = new ApplicationOAuthProvider(PublicClientId),
            AuthorizeEndpointPath = new PathString("/api/v1/account/externallogin"),
            AccessTokenExpireTimeSpan = TimeSpan.FromDays(14),
        };

        // Enable the application to use bearer tokens to authenticate users
        app.UseOAuthBearerTokens(OAuthOptions);

        DataProtectionProvider = app.GetDataProtectionProvider();
    }
}
```

**Comment by tillig** [comment]
Hello! Thanks for stopping in. We're admittedly a bit swamped right now trying to get .NET Core support working, so it may be a bit before we can fully repro this and figure it out.

Generally usage questions ("How do I do X?" "I know Y I should be working, but...") are really good on StackOverflow - we have a great set of folks out there (including us on the project!) monitoring the tag "autofac" over there. With more people, you can get a faster answer.

Otherwise, we'll do what we can as fast as we can, but there is quite a backlog we're working through so it may not be super soon.

**Comment by joelmdev** [comment]
SO question here: http://stackoverflow.com/questions/37826551/authorization-with-asp-net-identity-autofac-owin-integration

I'll xpost solution wherever it arises.

**Comment by joelmdev** [comment]
@tillig instead of taking the time to debug my configuration, can you point me towards an example configuration that works with authentication and authorization? I even tried slapping an AuthorizeAttribute on an API method in a [simple project that you helped out with](https://github.com/AkosLukacs/Autofac-OWIN-MVC) but ran into similar problems to my own.

**Comment by tillig** [comment]
I don't have a full sample like that anywhere I'm aware of. (I totally forgot about that project you found - nice spelunking to locate that!)

You didn't mention whether it was MVC controllers that weren't working or Web API controllers not working. That may help narrow down the issue.

Just some things I'm looking at in your code that _may or may not_ be part of the challenge:
- MVC5 doesn't really run in the OWIN pipeline, but Web API does. Which is to say, you can run OWIN _in conjunction_ with MVC5, but MVC5 itself isn't added to the pipeline as middleware in same way as other middleware is added. Sometimes this can cause things to run out of order.
- I usually register the [AutofacWebTypesModule](https://github.com/autofac/Autofac.Mvc/blob/develop/src/Autofac.Integration.Mvc/AutofacWebTypesModule.cs) in my apps and if I need something based on `HttpContext` I'll resolve an `HttpContextBase` and use that rather than tie directly to `HttpContext.Current`. If there are any async/await synchronization context issues, that can help because it'll ensure that - at least for the duration of a request - you'll always resolve the same `HttpContextBase` from the request lifetime.
- I'm not sure what happens in `WebApiConfig` but that may be worth a look.

Again, I'm not saying any of those things are problems at all, just those are the first things I'd start poking at if I were debugging the issue.

**Comment by joelmdev** [comment]
It is Web API that was failing on Auth. I followed the code in the aforementioned example project in terms of the registration order for the OWIN middlewares. The latest answer on the [SO question](http://stackoverflow.com/questions/37826551/authorization-with-asp-net-identity-autofac-owin-integration/37839448#37839448) suggested that my registrations were out of order. I tried the answerer's suggestion and it fixed the issue for Web API, but caused the exact same issue to pop up in MVC auth. After scratching my head as to why the issue would move I ended up with the following registration order:

```
app.UseAutofacMiddleware(container);
ConfigureAuth(app);
app.UseAutofacWebApi(config);
app.UseAutofacMvc();
app.UseWebApi(config);
ConfigureAuth(app);
```

Notice that I'm calling `ConfigureAuth(app)` twice. This allows auth to work correctly for both MVC and WebAPI but I am absolutely stumped as to why it works, and I can't imagine that it's a good idea. 

Can you provide any insight?

**Comment by bgabbasov** [comment]
Hi. I ran into the same issue. Thank you, you helped me a lot. I have a question. 

How did you manage getting ApplicationUserManager inside ApplicationOAuthProvider? You are creating without passing any additional parameters here:

`Provider = new ApplicationOAuthProvider(PublicClientId)`

and I don't understand how this line works in your case:

`var userManager = context.OwinContext.GetUserManager<ApplicationUserManager>();`

I manager this by adding supplying dependency resolver to the ApplicationOAuthProvider:

`Provider = new ApplicationOAuthProvider(PublicClientId, config.DependencyResolver)`

and then resolving ApplicationUserManager inside ApplicationOAuthProvider using the dependency resolver:

`var userManager = (ApplicationUserManager)_dependencyResolver.GetService(typeof(ApplicationUserManager));`.

And I am not sure if this is correct way to do this.

**Comment by tillig** [comment]
Is there a _simple_ repro of this somewhere we can look at? I recognize there's a requirement for some level of complexity given it's auth providers and all that, but if there's something with, like...

- One controller for MVC
- One controller for Web API
- As _little startup as possible_ to illustrate the problem and _no more_ (e.g., no `SecurityStampValidator` and all that - just the stuff that actually shows the problem; if OAuth isn't required to show the problem and Basic auth also fails, use that)

Without a repro, there's not much we can do. I see code snippets, but there's a lot that I'm sure isn't affecting things, like `EmailService` registrations and so on.

**Comment by tillig** [comment]
Given there's been no update here and there are other apps (including a lot of my own apps) that don't have this issue, I'm going to close it. If there's a simple repro where it can be seen, awesome.

I would encourage updates [to the StackOverflow question](https://stackoverflow.com/questions/37826551/authorization-with-asp-net-identity-autofac-owin-integration) so the most folks can benefit from it.
