### ISSUE TITLE
Support Autofac 4 Ecosystem

### ISSUE THREAD

**Issue by helloitszak** [autofac/Autofac.WebApi.Owin#4]
According to the guide [here](1), when using Autofac with WebApi2 and OWIN you need the `Autofac.Owin` and `Autofac.WebApi2.Owin.` However, the `Autofac.WebApi2.Owin` package has a dependency on `Autofac`, `Autofac.Owin` and `Autofac.WebApi2` that are all `< 4.0.0`.

Right now I can get by using the `3.x` releases of Autofac, but it is preventing me from upgrading to the latest Autofac. Is there plans to support the rest of Autofac 4 with this package?

**Comment by tillig** [comment]
Yup, we are slowly and surely getting through the 23-odd integration libraries. [You can read/subscribe this issue to follow along if you like.](https://github.com/autofac/Autofac/issues/594)

**Comment by helloitszak** [comment]
Fantastic! Thank you for your quick reply. I will follow along in that other thread.
