### ISSUE TITLE
Question: responsibilities of the DependencyResolver and DependencyScope?

### ISSUE THREAD

**Issue by mderriey** [autofac/Autofac.WebApi.Owin#6]
Hi,

I was looking a bit into the internals of how Autofac wires up the OWIN lifetime scope with Web API, and I was very surprised to see that the `DependencyScope` is created from the OWIN lifetime scope and stored in the `HttpRequestMessage` properties - [code](https://github.com/autofac/Autofac.WebApi.Owin/blob/fcc95d0d4c3419c78b7c36f7296429ed623caf42/src/Autofac.Integration.WebApi.Owin/DependencyScopeHandler.cs#L27).

After fiddling in ASP.NET Web API source code, I indeed found that we look for a dependency scope in the current `HttpRequestMessage` first, and only if we don't find it then create one from the `DependencyResolver` - [code](https://github.com/ASP-NET-MVC/aspnetwebstack/blob/4e40cdef9c8a8226685f95ef03b746bc8322aa92/src/System.Web.Http/HttpRequestMessageExtensions.cs#L89).

So am I right when I say that when using ASP.NET Web API and OWIN, the `BeginScope` method of `AutofacWebApiDependencyResolver` is never called? It would only be called if we use the `System.Web`-based version of Web API?

If so, do you know when the `AutofacWebApiDependencyResolver` is being used by Web API? I tried looking in the source code but couldn't really find an answer.

Cheers.

**Comment by tillig** [comment]
[Basically, the whole notion of per-request lifetimes](http://autofac.readthedocs.io/en/latest/faq/per-request-scope.html) is that _at some point in time in the request_ a specifically-named lifetime scope is created and used as the basis for resolving services during that request. To get that to happen, you need to store the lifetime scope in a common location so both OWIN and non-OWIN integration will work. In the case of Web API, that's the request message.

Your analysis, then, is correct - the dependency resolver will not be the thing that creates the request lifetime if you're using OWIN-only.

The dependency resolver is used by other things in the stack, though, for example, whenever you need a service like `IHttpActionInvoker` - you can _either_ set it statically on the `HttpConfiguration.Services` collection, or you can [let it be resolved from the dependency resolver](https://github.com/ASP-NET-MVC/aspnetwebstack/blob/4e40cdef9c8a8226685f95ef03b746bc8322aa92/src/System.Web.Http/Services/DefaultServices.cs#L201). Those services do _not_ come from the per-request scope. If you search the aspnetwebstack code for uses of `IDependencyResolver` you'll see where the `AutofacWebApiDependencyResolver` might be used outside of just creating a request scope.

**Comment by mderriey** [comment]
Thanks heaps for taking the time to answer my question! Merry 🎄!
